//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TrayIcon.rc
//
#define IDB_BITMAP1                     1000
#define IDI_DefaultIcon                 1001
#define IDI_BLANK_BLACK                 1003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1006
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
